// SPDX-License-Identifier: MIT OR Apache-2.0
//! Shell-completion generation and the `cheat` sheet (V2-M6, #598).
//!
//! Completion is generated from ONE declarative description of the command tree ([`COMMAND_TREE`]),
//! which is the single source of truth: the bash, zsh, and fish generators all walk the SAME table,
//! so a completion can never drift from a hand-maintained per-shell list. The `cheat` command prints
//! a concise cheat-sheet of the common flows, also derived from generic, org-agnostic examples.
//!
//! There is no `clap` in this CLI (the parser is hand-rolled), so completion is generated by hand
//! from the tree rather than by a derive macro — but it is still data-driven from a single table,
//! which is the property that prevents drift. A test (`completion_lists_every_top_level_subcommand`)
//! asserts the tree covers every dispatched subcommand, so a new verb that forgets to register here
//! fails CI rather than silently shipping without completion.

use crate::CliError;
use std::fmt::Write as _;
use std::io::Write;

/// One node of the command tree: a (sub)command name, its flags, and any nested subcommands.
pub(crate) struct Cmd {
    /// The literal subcommand token (e.g. `"pub"`, `"consumer-reset"`).
    pub name: &'static str,
    /// A one-line description, shown in zsh/fish completion and the cheat sheet.
    pub about: &'static str,
    /// The flags this command accepts (the literal `--xxx` strings, including aliases).
    pub flags: &'static [&'static str],
    /// Nested subcommands (e.g. `admin consumer-reset`), empty for a leaf command.
    pub subs: &'static [Cmd],
}

/// Flags accepted by EVERY command via the global pre-dispatch handling (`--json`) plus the
/// universal help flags. Offered on every command in completion.
pub(crate) const GLOBAL_FLAGS: &[&str] = &["--json", "--help", "-h"];

/// The single source-of-truth command tree. The completion generators and the coverage test both
/// walk this; keep it in sync with `fn run` dispatch (the coverage test enforces it).
pub(crate) const COMMAND_TREE: &[Cmd] = &[
    Cmd {
        name: "pub",
        about: "Publish a message (payload from arg or stdin)",
        flags: &["--addr", "--key"],
        subs: &[],
    },
    Cmd {
        name: "sub",
        about: "Consume messages from a group",
        flags: &[
            "--addr",
            "--group",
            "--max",
            "--ack",
            "--nack",
            "--term",
            "--delay-ms",
        ],
        subs: &[],
    },
    Cmd {
        name: "cumulative-ack",
        about: "Cumulatively ack a group up to an offset",
        flags: &["--addr", "--group", "--up-to"],
        subs: &[],
    },
    Cmd {
        name: "serve",
        about: "Run the broker",
        // The most operationally common serve flags (the full set is in `ironbus help`); listing
        // every one of the 60+ here would bloat completion without aiding the common path.
        flags: &[
            "--data-dir",
            "--storage",
            "--addr",
            "--config",
            "--profile",
            "--health-addr",
            "--enable-admin",
            "--max-connections",
            "--max-total-bytes",
            "--ephemeral-loss-ack",
        ],
        subs: &[],
    },
    Cmd {
        name: "admin",
        about: "Administrative operations",
        flags: &["--health-addr", "--addr"],
        subs: &[
            Cmd {
                name: "consumer-reset",
                about: "Reset a group's committed offset",
                flags: &["--data-dir", "--group", "--to"],
                subs: &[],
            },
            Cmd {
                name: "dlq-redrive",
                about: "Redrive dead-lettered records",
                flags: &["--data-dir"],
                subs: &[],
            },
        ],
    },
    Cmd {
        name: "peek",
        about: "Read records from a data dir (offline)",
        flags: &["--data-dir", "--from-offset", "--offset", "--limit"],
        subs: &[],
    },
    Cmd {
        name: "dump",
        about: "Dump every durable record (offline)",
        flags: &["--data-dir", "--limit", "--dlq", "--raw", "--require-dict"],
        subs: &[],
    },
    Cmd {
        name: "scrub",
        about: "Scan a data dir for corruption (offline)",
        flags: &["--data-dir"],
        subs: &[],
    },
    Cmd {
        name: "verify",
        about: "Verify data-dir integrity (offline)",
        flags: &["--data-dir"],
        subs: &[],
    },
    Cmd {
        name: "repair",
        about: "Repair a corrupt data dir (offline)",
        flags: &["--data-dir", "--apply", "--force"],
        subs: &[],
    },
    Cmd {
        name: "top",
        about: "Live broker / data-dir dashboard",
        flags: &[
            "--addr",
            "--health-addr",
            "--data-dir",
            "--interval",
            "--once",
            "--no-color",
        ],
        subs: &[],
    },
    Cmd {
        name: "bench",
        about: "Benchmark the broker",
        flags: &[
            "--mode",
            "--duration",
            "--count",
            "--rate",
            "--payload-bytes",
            "--payload-shape",
            "--fetch-batch",
            "--group",
            "--no-fsync",
            "--pubwindow",
            "--stream",
            "--storage",
            "--per-message-ack",
            "--addr",
            "--i-understand-this-is-live",
        ],
        subs: &[],
    },
    Cmd {
        name: "upgrade",
        about: "Atomically swap in a new binary",
        flags: &["--new-binary", "--dest", "--max-failed-starts"],
        subs: &[],
    },
    Cmd {
        name: "rollback",
        about: "Roll back to the previous binary",
        flags: &["--dest"],
        subs: &[],
    },
    Cmd {
        name: "record-start",
        about: "Drive the failed-start counter (systemd)",
        flags: &[
            "--dest",
            "--failed",
            "--ok",
            "--check",
            "--max-failed-starts",
        ],
        subs: &[],
    },
    Cmd {
        name: "migrate",
        about: "Gate an on-disk format migration",
        flags: &["--data-dir", "--allow"],
        subs: &[],
    },
    Cmd {
        name: "dict",
        about: "Compression-dictionary lifecycle (feature: zstd)",
        flags: &[],
        subs: &[
            Cmd {
                name: "train",
                about: "Train a dictionary from a sample corpus",
                flags: &[
                    "--type",
                    "--samples",
                    "--out",
                    "--target-dict-bytes",
                    "--min-samples",
                ],
                subs: &[],
            },
            Cmd {
                name: "install",
                about: "Install a dictionary into a data dir",
                flags: &["--data-dir", "--dict"],
                subs: &[],
            },
            Cmd {
                name: "ls",
                about: "List installed dictionaries",
                flags: &["--data-dir"],
                subs: &[],
            },
        ],
    },
    Cmd {
        name: "context",
        about: "Manage named connection profiles",
        flags: &[],
        subs: &[
            Cmd {
                name: "create",
                about: "Create (or update) a context",
                flags: &[
                    "--addr",
                    "--token",
                    "--tls-ca",
                    "--tls-server-name",
                    "--data-dir",
                    "--use",
                ],
                subs: &[],
            },
            Cmd {
                name: "use",
                about: "Switch the current context",
                flags: &[],
                subs: &[],
            },
            Cmd {
                name: "list",
                about: "List all contexts",
                flags: &[],
                subs: &[],
            },
            Cmd {
                name: "show",
                about: "Show one context (token redacted)",
                flags: &[],
                subs: &[],
            },
            Cmd {
                name: "rm",
                about: "Remove a context",
                flags: &[],
                subs: &[],
            },
            Cmd {
                name: "current",
                about: "Print the current context name",
                flags: &[],
                subs: &[],
            },
        ],
    },
    Cmd {
        name: "completion",
        about: "Generate a shell-completion script",
        flags: &[],
        subs: &[],
    },
    Cmd {
        name: "cheat",
        about: "Print a concise usage cheat-sheet",
        flags: &[],
        subs: &[],
    },
    Cmd {
        name: "version",
        about: "Print the build version",
        flags: &[],
        subs: &[],
    },
    Cmd {
        name: "help",
        about: "Print full usage",
        flags: &[],
        subs: &[],
    },
];

/// The supported completion shells.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Shell {
    Bash,
    Zsh,
    Fish,
}

impl Shell {
    fn parse(s: &str) -> Result<Self, CliError> {
        match s {
            "bash" => Ok(Shell::Bash),
            "zsh" => Ok(Shell::Zsh),
            "fish" => Ok(Shell::Fish),
            other => Err(CliError::Usage(format!(
                "unknown shell `{other}` (expected bash|zsh|fish)"
            ))),
        }
    }
}

/// Runs `ironbus completion <bash|zsh|fish>`, writing the generated script to `out`.
///
/// # Errors
/// A missing or unknown shell argument is a [`CliError::Usage`].
pub(crate) fn run_completion(args: &[String], out: &mut impl Write) -> Result<(), CliError> {
    let shell = match args {
        [s] => Shell::parse(s)?,
        [] => {
            return Err(CliError::Usage(
                "completion requires a shell: bash|zsh|fish".to_string(),
            ))
        }
        _ => {
            return Err(CliError::Usage(
                "completion takes a single shell argument".to_string(),
            ))
        }
    };
    let script = generate(shell, COMMAND_TREE);
    out.write_all(script.as_bytes())?;
    Ok(())
}

/// Generates the completion script for `shell` from `tree`.
fn generate(shell: Shell, tree: &[Cmd]) -> String {
    match shell {
        Shell::Bash => generate_bash(tree),
        Shell::Zsh => generate_zsh(tree),
        Shell::Fish => generate_fish(tree),
    }
}

/// Collects every top-level subcommand name (the first completion level).
fn top_names(tree: &[Cmd]) -> Vec<&'static str> {
    tree.iter().map(|c| c.name).collect()
}

/// bash completion: a single `complete -F` function. It offers the top-level subcommands at word 1,
/// then a command's flags (plus its nested subcommands) once a subcommand is recognized. The global
/// `--json`/`--help` flags are offered everywhere.
fn generate_bash(tree: &[Cmd]) -> String {
    let mut s = String::new();
    s.push_str("# bash completion for ironbus — generated from the live command tree.\n");
    s.push_str("# Source this file, or install it under your bash-completion.d directory.\n");
    s.push_str("_ironbus() {\n");
    s.push_str("    local cur prev words cword\n");
    s.push_str("    _init_completion 2>/dev/null || { cur=\"${COMP_WORDS[COMP_CWORD]}\"; prev=\"${COMP_WORDS[COMP_CWORD-1]}\"; }\n");
    let _ = writeln!(s, "    local top=\"{}\"", top_names(tree).join(" "));
    let _ = writeln!(s, "    local global=\"{}\"", GLOBAL_FLAGS.join(" "));
    s.push_str("    if [ \"$COMP_CWORD\" -eq 1 ]; then\n");
    s.push_str("        COMPREPLY=( $(compgen -W \"$top\" -- \"$cur\") )\n");
    s.push_str("        return 0\n");
    s.push_str("    fi\n");
    s.push_str("    local cmd=\"${COMP_WORDS[1]}\"\n");
    s.push_str("    case \"$cmd\" in\n");
    for cmd in tree {
        let _ = writeln!(s, "        {})", cmd.name);
        if cmd.subs.is_empty() {
            let flags = join_flags(cmd.flags);
            let _ = writeln!(
                s,
                "            COMPREPLY=( $(compgen -W \"{flags} $global\" -- \"$cur\") ) ;;"
            );
        } else {
            // Offer the nested subcommand names AND the parent's own flags + the subs' flags.
            let subnames: Vec<&str> = cmd.subs.iter().map(|c| c.name).collect();
            let mut all_flags: Vec<&str> = cmd.flags.to_vec();
            for sub in cmd.subs {
                all_flags.extend_from_slice(sub.flags);
            }
            all_flags.sort_unstable();
            all_flags.dedup();
            let _ = writeln!(
                s,
                "            COMPREPLY=( $(compgen -W \"{} {} $global\" -- \"$cur\") ) ;;",
                subnames.join(" "),
                all_flags.join(" ")
            );
        }
    }
    s.push_str("        *) COMPREPLY=( $(compgen -W \"$global\" -- \"$cur\") ) ;;\n");
    s.push_str("    esac\n");
    s.push_str("    return 0\n");
    s.push_str("}\n");
    s.push_str("complete -F _ironbus ironbus\n");
    s
}

/// zsh completion: a `#compdef` function using `_describe`/`_arguments`. Descriptions come from the
/// tree's `about` text.
fn generate_zsh(tree: &[Cmd]) -> String {
    let mut s = String::new();
    s.push_str("#compdef ironbus\n");
    s.push_str("# zsh completion for ironbus — generated from the live command tree.\n");
    s.push_str("_ironbus() {\n");
    s.push_str("    local -a _top\n");
    s.push_str("    _top=(\n");
    for cmd in tree {
        let _ = writeln!(s, "        '{}:{}'", cmd.name, zsh_escape(cmd.about));
    }
    s.push_str("    )\n");
    s.push_str("    if (( CURRENT == 2 )); then\n");
    s.push_str("        _describe 'command' _top\n");
    s.push_str("        return\n");
    s.push_str("    fi\n");
    s.push_str("    case \"${words[2]}\" in\n");
    for cmd in tree {
        let _ = writeln!(s, "        {})", cmd.name);
        if !cmd.subs.is_empty() {
            s.push_str("            local -a _subs\n");
            s.push_str("            _subs=(\n");
            for sub in cmd.subs {
                let _ = writeln!(
                    s,
                    "                '{}:{}'",
                    sub.name,
                    zsh_escape(sub.about)
                );
            }
            s.push_str("            )\n");
            s.push_str("            if (( CURRENT == 3 )); then _describe 'subcommand' _subs; return; fi\n");
        }
        let mut flags: Vec<&str> = cmd.flags.to_vec();
        for sub in cmd.subs {
            flags.extend_from_slice(sub.flags);
        }
        flags.extend_from_slice(GLOBAL_FLAGS);
        flags.sort_unstable();
        flags.dedup();
        let specs: Vec<String> = flags.iter().map(|f| format!("'{f}'")).collect();
        let _ = writeln!(s, "            _values 'flag' {} ;;", specs.join(" "));
    }
    s.push_str("    esac\n");
    s.push_str("}\n");
    s.push_str("_ironbus \"$@\"\n");
    s
}

/// fish completion: one `complete -c ironbus` line per subcommand and per flag, conditioned with
/// `__fish_use_subcommand` / `__fish_seen_subcommand_from`.
fn generate_fish(tree: &[Cmd]) -> String {
    let mut s = String::new();
    s.push_str("# fish completion for ironbus — generated from the live command tree.\n");
    for cmd in tree {
        let _ = writeln!(
            s,
            "complete -c ironbus -n __fish_use_subcommand -f -a {} -d '{}'",
            cmd.name,
            fish_escape(cmd.about)
        );
    }
    for cmd in tree {
        for sub in cmd.subs {
            let _ = writeln!(
                s,
                "complete -c ironbus -n '__fish_seen_subcommand_from {}' -f -a {} -d '{}'",
                cmd.name,
                sub.name,
                fish_escape(sub.about)
            );
        }
        let mut flags: Vec<&str> = cmd.flags.to_vec();
        for sub in cmd.subs {
            flags.extend_from_slice(sub.flags);
        }
        flags.extend_from_slice(GLOBAL_FLAGS);
        flags.sort_unstable();
        flags.dedup();
        for f in flags {
            let long = f.trim_start_matches('-');
            let _ = writeln!(
                s,
                "complete -c ironbus -n '__fish_seen_subcommand_from {}' -l {}",
                cmd.name, long
            );
        }
    }
    s
}

/// Escapes single quotes for a zsh single-quoted string.
fn zsh_escape(s: &str) -> String {
    s.replace('\'', "'\\''")
}

/// Escapes single quotes for a fish single-quoted string.
fn fish_escape(s: &str) -> String {
    s.replace('\'', "\\'")
}

/// Joins a command's flags into a space-separated word list (for bash `compgen -W`).
fn join_flags(flags: &[&str]) -> String {
    flags.join(" ")
}

/// The cheat-sheet text: a concise tour of the common flows, with ONLY generic, org-agnostic
/// examples (`localhost:7000`, `example.com`). Printed by `ironbus cheat`.
const CHEAT: &str = "\
ironbus cheat-sheet — common flows
==================================

START A BROKER
  ironbus serve --data-dir ./data                 # durable, loopback (127.0.0.1:7777)
  ironbus serve --data-dir ./data --addr 0.0.0.0:7000 --enable-admin
  ironbus serve --storage memory --ephemeral-loss-ack --max-total-bytes 256MiB

PRODUCE / CONSUME
  echo 'hello' | ironbus pub                       # payload from stdin
  ironbus pub --key orders 'payload'               # payload as an argument
  ironbus sub --group workers --max 10 --ack       # fetch up to 10 and ack
  ironbus cumulative-ack --group workers --up-to 100

INSPECT A DATA DIR (offline, no broker)
  ironbus peek  --data-dir ./data --limit 20
  ironbus dump  --data-dir ./data --json | ...     # NDJSON of every record
  ironbus verify --data-dir ./data                 # integrity check
  ironbus scrub --data-dir ./data                  # report corruption spans
  ironbus repair --data-dir ./data --apply --force

LIVE DASHBOARD
  ironbus top --addr localhost:7000
  ironbus top --data-dir ./data --once --no-color

CONNECTION CONTEXTS (named profiles; flags always override)
  ironbus context create prod --addr example.com:7000 --token <tok> --use
  ironbus context create local --addr localhost:7000
  ironbus context list
  ironbus context use local
  ironbus context current
  ironbus context show prod                         # token is redacted
  # any client verb now resolves its --addr from the current context:
  ironbus sub --group workers                       # dials the current context's addr

MACHINE-READABLE OUTPUT (uniform envelope, stable exit codes)
  ironbus --json verify --data-dir ./data          # {\"schema\":\"ironbus.cli.v1\",\"ok\":...}
  # exit: 0 ok | 1 usage | 2 not-found | 3 handled-corruption | 4 corrupt | 5 unreachable | 70 internal

SHELL COMPLETION
  ironbus completion bash > /etc/bash_completion.d/ironbus
  ironbus completion zsh  > ~/.zsh/completions/_ironbus
  ironbus completion fish > ~/.config/fish/completions/ironbus.fish

  Run `ironbus help` for the full flag reference.
";

/// Runs `ironbus cheat`, printing the cheat-sheet.
///
/// # Errors
/// Rejects any argument (the cheat sheet takes none) as a [`CliError::Usage`].
pub(crate) fn run_cheat(args: &[String], out: &mut impl Write) -> Result<(), CliError> {
    if !args.is_empty() {
        return Err(CliError::Usage("cheat takes no arguments".to_string()));
    }
    out.write_all(CHEAT.as_bytes())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn args(v: &[&str]) -> Vec<String> {
        v.iter().map(|s| (*s).to_string()).collect()
    }

    /// The tree must cover EVERY top-level subcommand the dispatcher handles, so completion can
    /// never silently omit a verb. This is the anti-drift guard.
    #[test]
    fn completion_lists_every_top_level_subcommand() {
        // The set the dispatcher in `fn run` matches (see main.rs). Aliases (`--help`, `-V`, etc.)
        // are NOT separate commands and are excluded.
        let dispatched = [
            "pub",
            "sub",
            "cumulative-ack",
            "serve",
            "admin",
            "peek",
            "dump",
            "scrub",
            "verify",
            "repair",
            "top",
            "bench",
            "upgrade",
            "rollback",
            "record-start",
            "migrate",
            "dict",
            "context",
            "completion",
            "cheat",
            "version",
            "help",
        ];
        let listed = top_names(COMMAND_TREE);
        for d in dispatched {
            assert!(
                listed.contains(&d),
                "command `{d}` is dispatched but missing from COMMAND_TREE (completion would drift)"
            );
        }
    }

    #[test]
    fn bash_completion_is_generated_for_the_tree() {
        let mut buf = Vec::new();
        run_completion(&args(&["bash"]), &mut buf).unwrap();
        let script = String::from_utf8(buf).unwrap();
        assert!(script.contains("complete -F _ironbus ironbus"));
        // Every top-level command appears in the case dispatch.
        for cmd in COMMAND_TREE {
            assert!(
                script.contains(&format!("        {})", cmd.name)),
                "bash completion missing case for `{}`",
                cmd.name
            );
        }
        // A nested subcommand is offered.
        assert!(script.contains("consumer-reset"));
        // The global flag is present.
        assert!(script.contains("--json"));
    }

    #[test]
    fn zsh_completion_is_generated_for_the_tree() {
        let mut buf = Vec::new();
        run_completion(&args(&["zsh"]), &mut buf).unwrap();
        let script = String::from_utf8(buf).unwrap();
        assert!(script.starts_with("#compdef ironbus"));
        assert!(script.contains("'pub:"));
        assert!(script.contains("consumer-reset"));
    }

    #[test]
    fn fish_completion_is_generated_for_the_tree() {
        let mut buf = Vec::new();
        run_completion(&args(&["fish"]), &mut buf).unwrap();
        let script = String::from_utf8(buf).unwrap();
        assert!(script.contains("complete -c ironbus -n __fish_use_subcommand -f -a pub"));
        assert!(script.contains("'__fish_seen_subcommand_from admin' -f -a consumer-reset"));
    }

    #[test]
    fn unknown_shell_is_a_usage_error() {
        let mut buf = Vec::new();
        let e = run_completion(&args(&["powershell"]), &mut buf).unwrap_err();
        assert_eq!(e.exit_code(), crate::EXIT_USAGE);
    }

    #[test]
    fn missing_shell_is_a_usage_error() {
        let mut buf = Vec::new();
        let e = run_completion(&args(&[]), &mut buf).unwrap_err();
        assert_eq!(e.exit_code(), crate::EXIT_USAGE);
    }

    #[test]
    fn cheat_prints_and_takes_no_args() {
        let mut buf = Vec::new();
        run_cheat(&[], &mut buf).unwrap();
        let text = String::from_utf8(buf).unwrap();
        assert!(text.contains("ironbus cheat-sheet"));
        assert!(text.contains("CONNECTION CONTEXTS"));
        assert!(text.contains("SHELL COMPLETION"));
        // A stray argument is rejected.
        let mut buf2 = Vec::new();
        assert_eq!(
            run_cheat(&args(&["x"]), &mut buf2).unwrap_err().exit_code(),
            crate::EXIT_USAGE
        );
    }

    /// Completion output is deterministic: generating twice yields identical bytes (no map/iteration
    /// nondeterminism), which a downstream snapshot or install step relies on.
    #[test]
    fn completion_generation_is_deterministic() {
        for shell in ["bash", "zsh", "fish"] {
            let mut a = Vec::new();
            let mut b = Vec::new();
            run_completion(&args(&[shell]), &mut a).unwrap();
            run_completion(&args(&[shell]), &mut b).unwrap();
            assert_eq!(a, b, "{shell} completion is not deterministic");
        }
    }
}
