[package]
name = "ironbus-core"
description = "Core types and IO-free logic for IronBus."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
crc32c = "0.6"

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
