// SPDX-License-Identifier: MIT OR Apache-2.0
//! The conformance-corpus regression gate (#45).
//!
//! This integration test drives the deterministic generator in `conformance/mod.rs` and:
//!
//! 1. Reproduces the checked-in corpus bytes EXACTLY: every fixture's freshly generated bytes
//!    must equal the bytes committed under `tests/corpus/<name>.bin`. An unintended format
//!    change (a field width, an endianness, a flag derivation) changes the bytes and fails
//!    here, so the corpus is a real regression gate, not just documentation. Setting
//!    `IRONBUS_REGENERATE_CORPUS=1` rewrites the files instead of asserting (the documented
//!    regeneration path); it is never set in CI, so the gate always asserts there.
//!
//! 2. Asserts each fixture decodes to its expected verdict (intact / torn-truncate /
//!    skip-and-report with the loss tuple / fail-closed reject), so the bytes and the verdict
//!    can never drift apart.
//!
//! 3. Reproduces the worked format dump documented for the versioning task (#126,
//!    docs/COMPATIBILITY.md and docs/CONTRACTS.md) and verifies it against the minimal-record
//!    corpus fixture.
//!
//! The cross-platform byte-identity guarantee rides on (1): because the checked-in bytes are
//! committed once and this test regenerates and compares them, running it on aarch64 and i686
//! (the existing musl and 32-bit CI matrices, which run `cargo test -p ironbus-core`) asserts
//! those architectures produce byte-identical output and each verifies the frozen CRCs. The
//! `byte_identity` test below makes the cross-CRC verification explicit.

#[path = "conformance/mod.rs"]
mod conformance;

use std::path::PathBuf;

use conformance::{
    corpus, decode_segment_records, digest_line, has_clean_footer, Fixture, Freeze, ReasonCode,
    Verdict,
};
use ironbus_core::codec::{decode, encode, DecodeError, RecordView};
use ironbus_core::format::{
    header_offsets, segment_header_offsets, RECORD_HEADER_CRC_RANGE, RECORD_HEADER_LEN,
    SEGMENT_HEADER_LEN,
};
use ironbus_core::segment::SegmentHeader;
use ironbus_core::types::{RecordFlags, Seq};

/// The directory holding the checked-in corpus `.bin` files, relative to this crate.
fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("corpus")
}

/// `true` when the test was asked to REWRITE the corpus rather than assert against it. This is
/// the documented regeneration path (`IRONBUS_REGENERATE_CORPUS=1 cargo test ...`); it is never
/// set in CI, so the gate always asserts there.
fn regenerating() -> bool {
    std::env::var_os("IRONBUS_REGENERATE_CORPUS").is_some()
}

#[test]
fn corpus_is_complete_and_named_uniquely() {
    let fixtures = corpus();
    // The acceptance criteria enumerate these fixtures; pin them by name so a future edit that
    // DROPS a case (regressing coverage) fails here, not silently.
    let expected_names = [
        "record_minimal",
        "record_key_only",
        "record_key_headers_payload",
        "record_compressed",
        "record_max_size",
        "record_compressed_over_threshold",
        "segment_sealed_with_footer",
        "segment_active_no_footer",
        "segment_torn_tail_mid_body",
        "segment_torn_tail_mid_trailer",
        "segment_mid_log_bit_flip",
        "segment_zero_window_tail",
        "record_newer_version_reject",
        "segment_header",
    ];
    let got: Vec<&str> = fixtures.iter().map(|f| f.name).collect();
    assert_eq!(
        got, expected_names,
        "the corpus fixture set or order changed"
    );

    // Names are unique (a duplicate would collide on disk).
    let mut seen = std::collections::BTreeSet::new();
    for f in &fixtures {
        assert!(seen.insert(f.name), "duplicate fixture name {}", f.name);
        assert!(!f.bytes.is_empty(), "fixture {} has no bytes", f.name);
    }
}

#[test]
fn generator_reproduces_the_checked_in_corpus_bytes_exactly() {
    let dir = corpus_dir();
    if regenerating() {
        std::fs::create_dir_all(&dir).expect("create corpus dir");
    }
    let mut mismatches = Vec::new();
    for f in corpus() {
        match f.freeze {
            Freeze::RawBytes => {
                let path = dir.join(format!("{}.bin", f.name));
                if regenerating() {
                    std::fs::write(&path, &f.bytes).expect("write fixture");
                    continue;
                }
                let on_disk = match std::fs::read(&path) {
                    Ok(b) => b,
                    Err(e) => {
                        mismatches.push(format!("{}: cannot read {}: {e}", f.name, path.display()));
                        continue;
                    }
                };
                if on_disk != f.bytes {
                    mismatches.push(format!(
                        "{}: generated {} bytes but the checked-in fixture is {} bytes (the v1 \
                         byte format drifted; if this is a deliberate format change, regenerate \
                         with IRONBUS_REGENERATE_CORPUS=1 and bump FORMAT_VERSION)",
                        f.name,
                        f.bytes.len(),
                        on_disk.len(),
                    ));
                }
            }
            Freeze::Digest => {
                // A digest-frozen fixture (the 16 MiB max-size record) commits a small text
                // digest instead of the raw blob. The digest is a pure function of the exact
                // bytes, so any drift changes it: still a byte-exact gate, just compact on disk.
                let path = dir.join(format!("{}.digest", f.name));
                let want = digest_line(&f.bytes);
                if regenerating() {
                    std::fs::write(&path, &want).expect("write digest");
                    continue;
                }
                let on_disk = match std::fs::read_to_string(&path) {
                    Ok(s) => s,
                    Err(e) => {
                        mismatches.push(format!("{}: cannot read {}: {e}", f.name, path.display()));
                        continue;
                    }
                };
                if on_disk != want {
                    mismatches.push(format!(
                        "{}: digest drifted\n  generated: {}  checked-in: {}\n(the v1 byte format \
                         drifted; regenerate with IRONBUS_REGENERATE_CORPUS=1 and bump \
                         FORMAT_VERSION if deliberate)",
                        f.name,
                        want.trim_end(),
                        on_disk.trim_end(),
                    ));
                }
            }
        }
    }
    assert!(
        mismatches.is_empty(),
        "corpus byte drift:\n{}",
        mismatches.join("\n")
    );

    // The corpus directory holds exactly the generated fixtures plus the README: no stale file a
    // deleted fixture left behind, and no extra committed artifact nobody generates.
    if !regenerating() {
        let mut names = std::collections::BTreeSet::new();
        for f in corpus() {
            match f.freeze {
                Freeze::RawBytes => names.insert(format!("{}.bin", f.name)),
                Freeze::Digest => names.insert(format!("{}.digest", f.name)),
            };
        }
        for entry in std::fs::read_dir(&dir).expect("read corpus dir") {
            let entry = entry.expect("dir entry");
            let path = entry.path();
            let ext = path.extension().and_then(|e| e.to_str());
            let file = entry.file_name().to_string_lossy().into_owned();
            if matches!(ext, Some("bin" | "digest")) {
                assert!(
                    names.contains(&file),
                    "stale corpus file with no generator: {file}"
                );
            }
        }
    }
}

#[test]
fn corpus_reason_codes_match_the_frozen_storage_codes() {
    // The corpus names recovery verdicts with its own `ReasonCode` mirror (so the core-crate
    // corpus does not depend on the storage crate). Pin its numeric codes to the FROZEN values
    // `ironbus_storage::loss::ReasonCode::code` assigns (TornTail = 1, CorruptRecordHeader = 2,
    // CorruptRecordBody = 3), so the mirror can never silently drift from the real codes. The
    // storage crate's own `reason_codes_are_stable_and_distinct` test pins the source of truth.
    assert_eq!(ReasonCode::TornTail.code(), 1);
    assert_eq!(ReasonCode::CorruptRecordHeader.code(), 2);
    assert_eq!(ReasonCode::CorruptRecordBody.code(), 3);
}

#[test]
fn every_fixture_decodes_to_its_expected_verdict() {
    for f in corpus() {
        assert_fixture_verdict(&f);
    }
}

/// Drives one fixture's bytes through the real decoder (or segment-structure decoder) and
/// asserts the outcome matches its declared [`Verdict`]. This is what binds the bytes to the
/// verdict: a byte change that flips the outcome fails here even if it slipped past the
/// byte-diff gate (it cannot, but the two checks are independent on purpose).
fn assert_fixture_verdict(f: &Fixture) {
    match &f.verdict {
        Verdict::IntactRecord(expected) => {
            let (view, consumed) = decode(&f.bytes)
                .unwrap_or_else(|e| panic!("{}: expected intact, got {e:?}", f.name));
            assert_eq!(consumed, f.bytes.len(), "{}: whole frame consumed", f.name);
            expected.assert_matches(&view);
        }
        Verdict::IntactSegmentHeader(expected) => assert_intact_segment_header(f, expected),
        Verdict::IntactSegment {
            records,
            has_footer,
        } => assert_intact_segment(f, records, *has_footer),
        Verdict::TornTruncate(loss) => assert_torn_truncate(f, loss),
        Verdict::SkipAndReport(loss) => assert_skip_and_report(f, loss),
        Verdict::FailClosedReject(expected_err) => {
            assert_eq!(
                decode(&f.bytes),
                Err(*expected_err),
                "{}: fail-closed reject",
                f.name
            );
        }
    }
}

/// Asserts a fixture's bytes decode to the expected standalone segment header.
fn assert_intact_segment_header(f: &Fixture, expected: &conformance::ExpectedSegmentHeader) {
    let h = SegmentHeader::decode(&f.bytes)
        .unwrap_or_else(|e| panic!("{}: segment header decode failed: {e:?}", f.name));
    assert_eq!(h.segment_id, expected.segment_id, "{}: segment_id", f.name);
    assert_eq!(h.base_seq.get(), expected.base_seq, "{}: base_seq", f.name);
    assert_eq!(
        h.base_offset.get(),
        expected.base_offset,
        "{}: base_offset",
        f.name
    );
    assert_eq!(
        h.created_unix_ms, expected.created_unix_ms,
        "{}: created_ms",
        f.name
    );
    assert_eq!(h.flags, expected.flags, "{}: flags", f.name);
}

/// Asserts a multi-record segment fixture decodes to the expected record sequence and footer state.
fn assert_intact_segment(f: &Fixture, records: &[conformance::ExpectedRecord], has_footer: bool) {
    // The header decodes.
    let _ = SegmentHeader::decode(&f.bytes)
        .unwrap_or_else(|e| panic!("{}: segment header decode failed: {e:?}", f.name));
    let (decoded, stop) = decode_segment_records(&f.bytes);
    assert_eq!(decoded, records, "{}: decoded record sequence", f.name);
    assert_eq!(
        has_clean_footer(&f.bytes),
        has_footer,
        "{}: footer presence",
        f.name
    );
    if has_footer {
        // A sealed segment's record region ends exactly where the footer begins.
        assert_eq!(
            stop,
            f.bytes.len() - ironbus_core::format::SEGMENT_FOOTER_LEN,
            "{}: records run up to the footer",
            f.name
        );
    }
}

/// Asserts a torn-tail fixture decodes as `Truncated` at the loss head with a valid prefix before it.
fn assert_torn_truncate(f: &Fixture, loss: &conformance::LossTuple) {
    // The torn last frame, decoded at its start, is Truncated: the declared frame runs past the
    // available bytes.
    let at = usize::try_from(loss.start).expect("offset fits usize");
    assert_eq!(
        decode(&f.bytes[at..]),
        Err(DecodeError::Truncated),
        "{}: torn tail decodes as Truncated",
        f.name
    );
    assert_eq!(loss.reason, ReasonCode::TornTail, "{}: torn reason", f.name);
    assert_eq!(
        loss.end,
        f.bytes.len() as u64,
        "{}: torn span ends at EOF",
        f.name
    );
    // Everything BEFORE the torn frame decodes cleanly (a valid prefix).
    let (records, stop) = decode_segment_records(&f.bytes);
    assert_eq!(
        stop as u64, loss.start,
        "{}: prefix ends at the torn head",
        f.name
    );
    assert!(!records.is_empty(), "{}: a valid prefix survives", f.name);
}

/// Asserts a corruption fixture decodes to a corruption error at the loss head, so recovery
/// skips-and-reports the declared loss tuple, with a valid prefix before it.
fn assert_skip_and_report(f: &Fixture, loss: &conformance::LossTuple) {
    // The corrupt frame, decoded at its start, is a corruption error (not Truncated and not a
    // clean record), so recovery skips it and reports the loss tuple.
    let at = usize::try_from(loss.start).expect("offset fits usize");
    let err = decode(&f.bytes[at..]).expect_err("corrupt frame must not decode clean");
    match loss.reason {
        ReasonCode::CorruptRecordBody => {
            assert_eq!(
                err,
                DecodeError::BadBodyCrc,
                "{}: body-corruption error",
                f.name
            );
        }
        ReasonCode::CorruptRecordHeader => {
            // A zeroed or clobbered header fails magic/version/CRC (any header-class error).
            assert!(
                matches!(
                    err,
                    DecodeError::BadMagic
                        | DecodeError::UnsupportedVersion(_)
                        | DecodeError::BadHeaderCrc
                        | DecodeError::Truncated
                ),
                "{}: header-class error, got {err:?}",
                f.name
            );
        }
        ReasonCode::TornTail => panic!("{}: TornTail is a torn-truncate, not a skip", f.name),
    }
    assert_eq!(
        loss.end,
        f.bytes.len() as u64,
        "{}: loss span ends at EOF",
        f.name
    );
    // The valid prefix before the corruption decodes; its length is the loss start.
    let (_, stop) = decode_segment_records(&f.bytes);
    assert_eq!(
        stop as u64, loss.start,
        "{}: prefix ends at the corrupt head",
        f.name
    );
}

#[test]
fn reproduces_the_worked_format_dump_from_the_versioning_task() {
    // The versioning task (#126) and docs/COMPATIBILITY.md cite the byte tables in
    // docs/CONTRACTS.md as the worked dump of the v1 record frame. There is no committed HEX
    // dump file, so we reproduce the dump HERE from the documented field offsets and verify it
    // against the minimal-record corpus fixture, byte for byte. A drift in either the documented
    // layout or the encoder fails this test.
    //
    // The minimal record: seq = 1, timestamp_ms = 1_700_000_000_000, no key, no headers,
    // payload = b"x", below the xxh3 threshold. Its frame is header(36) + body(1) + trailer(8).
    let minimal = corpus()
        .into_iter()
        .find(|f| f.name == "record_minimal")
        .expect("the minimal-record fixture exists");

    let bytes = &minimal.bytes;
    assert_eq!(bytes.len(), RECORD_HEADER_LEN + 1 + 8, "minimal frame size");

    // Reconstruct the header field by field FROM THE DOCUMENTED OFFSETS (CONTRACTS.md
    // "RecordHeader") and assert each lands where the doc says it does.
    // magic at [0, 2) = 0x4942 (bytes 0x42 0x49).
    assert_eq!(
        &bytes[header_offsets::MAGIC..header_offsets::MAGIC + 2],
        &[0x42, 0x49],
        "magic bytes b'B' b'I'"
    );
    assert_eq!(
        u16::from_le_bytes([
            bytes[header_offsets::MAGIC],
            bytes[header_offsets::MAGIC + 1]
        ]),
        0x4942,
        "magic u16"
    );
    // version at [2, 3) = 1.
    assert_eq!(bytes[header_offsets::VERSION], 1, "version byte");
    // flags at [3, 4) = 0 (no key, no xxh3, not compressed).
    assert_eq!(bytes[header_offsets::FLAGS], 0, "flags byte");
    // seq at [4, 12) = 1 LE.
    assert_eq!(read_u64(bytes, header_offsets::SEQ), 1, "seq");
    // timestamp at [12, 20).
    assert_eq!(
        read_u64(bytes, header_offsets::TIMESTAMP),
        1_700_000_000_000,
        "timestamp"
    );
    // key_len at [20, 24) = 0; hdr_len at [24, 28) = 0; payload_len at [28, 32) = 1.
    assert_eq!(read_u32(bytes, header_offsets::KEY_LEN), 0, "key_len");
    assert_eq!(read_u32(bytes, header_offsets::HDR_LEN), 0, "hdr_len");
    assert_eq!(
        read_u32(bytes, header_offsets::PAYLOAD_LEN),
        1,
        "payload_len"
    );
    // header_crc at [32, 36) = CRC32C over [0, 32).
    let expected_header_crc = crc32c::crc32c(&bytes[RECORD_HEADER_CRC_RANGE]);
    assert_eq!(
        read_u32(bytes, header_offsets::HEADER_CRC),
        expected_header_crc,
        "header_crc"
    );

    // body = the single payload byte 'x' at [36, 37).
    assert_eq!(bytes[RECORD_HEADER_LEN], b'x', "payload byte");

    // trailer: body_crc at [total-8, total-4) = CRC32C over the body; total_len at [total-4, total).
    let total = bytes.len();
    let body_crc = crc32c::crc32c(&bytes[RECORD_HEADER_LEN..=RECORD_HEADER_LEN]);
    assert_eq!(read_u32(bytes, total - 8), body_crc, "body_crc");
    assert_eq!(
        read_u32(bytes, total - 4) as usize,
        total,
        "total_len equals frame length"
    );

    // And the whole thing decodes back to the documented record.
    let (view, consumed) = decode(bytes).expect("minimal frame decodes");
    assert_eq!(consumed, total);
    assert_eq!(view.seq, Seq::new(1));
    assert_eq!(view.timestamp_ms, 1_700_000_000_000);
    assert_eq!(view.payload, b"x");
    assert!(view.key.is_empty() && view.headers.is_empty());
}

#[test]
fn byte_identity_and_cross_crc_verification() {
    // The cross-platform byte-identity gate, expressed as a test that runs on every CI arch
    // (x86_64 native, aarch64/armv7 musl, i686 32-bit). It encodes a FIXED set of logical
    // records and asserts:
    //   - the encoded bytes equal the checked-in corpus bytes (byte-identical across arches,
    //     since the checked-in bytes were frozen once), and
    //   - the header_crc and body_crc in those bytes verify (each arch re-derives and checks the
    //     CRCs the others wrote), so an endianness or alignment bug that only shows on aarch64 is
    //     caught here rather than in production on an edge box.
    for f in corpus() {
        if let Verdict::IntactRecord(_) = &f.verdict {
            // Re-encode the logical record from the decoded view and assert byte-identity with
            // the fixture: the encoder is endianness-explicit LE, so this must hold on every arch.
            let (view, _) = decode(&f.bytes).expect("intact fixture decodes");
            let mut reencoded = Vec::new();
            encode(&view, &mut reencoded).expect("re-encode");
            assert_eq!(
                reencoded, f.bytes,
                "{}: re-encode is byte-identical",
                f.name
            );

            // Cross-verify the header_crc over [0, 32).
            let stored_header_crc = read_u32(&f.bytes, header_offsets::HEADER_CRC);
            assert_eq!(
                crc32c::crc32c(&f.bytes[RECORD_HEADER_CRC_RANGE]),
                stored_header_crc,
                "{}: header_crc verifies",
                f.name
            );
            // Cross-verify the body_crc over the body byte range.
            let total = f.bytes.len();
            let body_crc_stored = read_u32(&f.bytes, total - 8);
            // The body runs from the header end to just before the xxh3 field (if any) + trailer.
            let body_len = body_len_of(&view);
            let body = &f.bytes[RECORD_HEADER_LEN..RECORD_HEADER_LEN + body_len];
            assert_eq!(
                crc32c::crc32c(body),
                body_crc_stored,
                "{}: body_crc verifies",
                f.name
            );
        }
    }

    // The segment fixtures' header CRCs verify too (the 64-byte structure, CRC over [0, 60)).
    for f in corpus() {
        let is_segment = matches!(
            f.verdict,
            Verdict::IntactSegmentHeader(_) | Verdict::IntactSegment { .. }
        );
        if is_segment && f.bytes.len() >= SEGMENT_HEADER_LEN {
            let stored = read_u32(&f.bytes, segment_header_offsets::HEADER_CRC);
            let computed = crc32c::crc32c(&f.bytes[ironbus_core::format::SEGMENT_HEADER_CRC_RANGE]);
            assert_eq!(computed, stored, "{}: segment header_crc verifies", f.name);
        }
    }
}

/// The stored-body length of a decoded record: key + headers + payload, the bytes the `body_crc`
/// covers.
fn body_len_of(v: &RecordView<'_>) -> usize {
    v.key.len() + v.headers.len() + v.payload.len()
}

/// Little-endian u32 read for the dump reconstruction (the codec's reader is crate-private).
fn read_u32(b: &[u8], at: usize) -> u32 {
    u32::from_le_bytes([b[at], b[at + 1], b[at + 2], b[at + 3]])
}

/// Little-endian u64 read for the dump reconstruction.
fn read_u64(b: &[u8], at: usize) -> u64 {
    let mut a = [0u8; 8];
    a.copy_from_slice(&b[at..at + 8]);
    u64::from_le_bytes(a)
}

// === Round-trip property tests over the full size space within the caps ======================

use proptest::prelude::*;

proptest! {
    // decode(encode(x)) == x over random key/header/payload sizes spanning the FULL space the
    // caps allow up to a tractable ceiling: keys and headers up to a few KiB, payloads from 0 up
    // past the xxh3 threshold, so both the with-field and without-field layouts are exercised.
    // This is the #45 "round-trip property tests cover random sizes within the caps" criterion;
    // it widens the existing codec proptests (which cap payload at ~1 KiB) to straddle the field
    // boundary and the larger interior space.
    #[test]
    fn round_trip_over_the_full_size_space(
        seq in any::<u64>(),
        ts in any::<u64>(),
        compressed in any::<bool>(),
        key in proptest::collection::vec(any::<u8>(), 0..4096),
        headers in proptest::collection::vec(any::<u8>(), 0..4096),
        // Payloads from empty to past the xxh3 threshold, so the body straddles the boundary.
        payload in proptest::collection::vec(any::<u8>(), 0..(70 * 1024)),
    ) {
        let flags = if compressed { RecordFlags::COMPRESSED } else { RecordFlags::EMPTY };
        let rec = RecordView {
            seq: Seq::new(seq),
            timestamp_ms: ts,
            flags,
            key: &key,
            headers: &headers,
            payload: &payload,
        };
        let mut buf = Vec::new();
        let n = encode(&rec, &mut buf).expect("in-cap record encodes");
        prop_assert_eq!(n, buf.len());

        // decode(encode(x)) == x.
        let (got, consumed) = decode(&buf).expect("encoded record decodes");
        prop_assert_eq!(consumed, buf.len());
        prop_assert_eq!(got.seq, rec.seq);
        prop_assert_eq!(got.timestamp_ms, rec.timestamp_ms);
        prop_assert_eq!(got.key, &key[..]);
        prop_assert_eq!(got.headers, &headers[..]);
        prop_assert_eq!(got.payload, &payload[..]);
        prop_assert_eq!(got.flags.contains(RecordFlags::COMPRESSED), compressed);
        prop_assert_eq!(got.flags.contains(RecordFlags::HAS_KEY), !key.is_empty());

        // Every emitted record passes the frozen read sequence: magic, version, header CRC,
        // length consistency, body CRC (and xxh3 when present). decode performing all of those
        // and returning Ok with the full consumed length is exactly that sequence passing.
        let body_len = key.len() + headers.len() + payload.len();
        let want_xxh3 = body_len >= ironbus_core::format::XXH3_PAYLOAD_THRESHOLD as usize;
        prop_assert_eq!(got.flags.contains(RecordFlags::HAS_XXH3), want_xxh3);

        // The streaming-recovery length helper agrees with decode on the full frame length, which
        // is the read sequence recovery actually runs (read the header, learn the length, decode).
        prop_assert_eq!(
            ironbus_core::codec::decoded_len(&buf[..RECORD_HEADER_LEN]).expect("header length"),
            consumed
        );
    }

    // A second leg pinned to the boundary: payloads that straddle the xxh3 threshold exactly,
    // built as fixed-byte runs so the run is large yet cheap, asserting the HAS_XXH3 flag agrees
    // with the body size and the frame still round-trips.
    #[test]
    fn round_trip_straddling_the_xxh3_threshold(
        seq in any::<u64>(),
        ts in any::<u64>(),
        delta in -16i64..=16i64,
        fill in any::<u8>(),
    ) {
        let threshold = i64::from(ironbus_core::format::XXH3_PAYLOAD_THRESHOLD);
        let len = usize::try_from((threshold + delta).max(0)).expect("non-negative length");
        let payload = vec![fill; len];
        let rec = RecordView {
            seq: Seq::new(seq),
            timestamp_ms: ts,
            flags: RecordFlags::EMPTY,
            key: b"",
            headers: b"",
            payload: &payload,
        };
        let mut buf = Vec::new();
        encode(&rec, &mut buf).expect("encodes");
        let (got, consumed) = decode(&buf).expect("decodes");
        prop_assert_eq!(consumed, buf.len());
        prop_assert_eq!(
            got.flags.contains(RecordFlags::HAS_XXH3),
            len >= ironbus_core::format::XXH3_PAYLOAD_THRESHOLD as usize
        );
        prop_assert_eq!(got.payload, &payload[..]);
    }
}
